# Generated by Django 4.1.3 on 2022-11-30 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='People',
            new_name='Personal_data',
        ),
        migrations.AlterModelOptions(
            name='personal_data',
            options={'verbose_name': 'Dado pessoal', 'verbose_name_plural': 'Dados pessoais'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='people',
            new_name='personal_data',
        ),
    ]
