# Generated by Django 4.1.3 on 2022-12-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_people_personal_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dependents',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='epis',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='feedbacks',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='scholarity',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='trainings',
        ),
        migrations.AddField(
            model_name='employee',
            name='benefits',
            field=models.ManyToManyField(to='core.benefits', verbose_name='Benifícios'),
        ),
        migrations.AddField(
            model_name='employee',
            name='dependents',
            field=models.ManyToManyField(to='core.dependents', verbose_name='Dependentes'),
        ),
        migrations.AddField(
            model_name='employee',
            name='epis',
            field=models.ManyToManyField(to='core.epis', verbose_name='EPIs'),
        ),
        migrations.AddField(
            model_name='employee',
            name='feedbacks',
            field=models.ManyToManyField(to='core.feedbacks', verbose_name='Feedbacks'),
        ),
        migrations.AddField(
            model_name='employee',
            name='scholarity',
            field=models.ManyToManyField(to='core.scholarity', verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='trainings',
            field=models.ManyToManyField(to='core.trainings', verbose_name='Treinamentos'),
        ),
    ]
