# Generated by Django 4.1.3 on 2022-12-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employee_benefits_remove_employee_dependents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.CharField(max_length=15, verbose_name='Salário'),
        ),
    ]
