# Generated by Django 4.1.3 on 2022-12-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_employee_benefits_alter_employee_dependents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dependents',
        ),
        migrations.AddField(
            model_name='personal_data',
            name='dependents',
            field=models.ManyToManyField(blank=True, to='core.dependents', verbose_name='Dependentes'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='core.benefits', verbose_name='Benifícios'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='epis',
            field=models.ManyToManyField(blank=True, to='core.epis', verbose_name='EPIs'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, to='core.feedbacks', verbose_name='Feedbacks'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='scholarity',
            field=models.ManyToManyField(blank=True, to='core.scholarity', verbose_name='Escolaridade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='trainings',
            field=models.ManyToManyField(blank=True, to='core.trainings', verbose_name='Treinamentos'),
        ),
    ]
